dist: xenial
sudo: required
language: python
cache:
  pip: true
  directories:
    - $HOME/.cache/pypy
matrix:
  include:
    - python: "3.4"
    - python: "3.5"
    - python: "3.5-dev"
    - python: "3.6"
    - python: "3.6-dev"
    - python: "3.7"
    - python: "3.7-dev"
    - python: "3.8-dev"
    - python: "pypy3.5"
      env: PYPY3_PYTHON_VERSION=3.5 PYPY3_VERSION=6.0.0 PYPY3_SHA256=07f16282d126abfa759702baea869b0f661aa97f4c553ebec66c624bda28155f
  allow_failures:
    - python: "3.5-dev"
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "3.8-dev"
    - python: "pypy3.5"
  fast_finish: true
before_install:
  - "sudo apt-get -q update"
  - "if [ $TRAVIS_PYTHON_VERSION != 'pypy3.5' ]; then pip install -U pip; fi"
  - "if [ $TRAVIS_PYTHON_VERSION = 'pypy3.5' ]; then mkdir -p ~/.cache/pypy && echo $PYPY3_SHA256  ~/.cache/pypy/pypy$PYPY3_PYTHON_VERSION-$PYPY3_VERSION-linux_x86_64-portable.tar.bz2 | sha256sum --status -c || curl -f -L https://bitbucket.org/squeaky/portable-pypy/downloads/pypy$PYPY3_PYTHON_VERSION-$PYPY3_VERSION-linux_x86_64-portable.tar.bz2 > ~/.cache/pypy/pypy$PYPY3_PYTHON_VERSION-$PYPY3_VERSION-linux_x86_64-portable.tar.bz2; fi"
  - "if [ $TRAVIS_PYTHON_VERSION = 'pypy3.5' ]; then echo $PYPY3_SHA256  ~/.cache/pypy/pypy$PYPY3_PYTHON_VERSION-$PYPY3_VERSION-linux_x86_64-portable.tar.bz2 | sha256sum --status -c && tar -xjf ~/.cache/pypy/pypy$PYPY3_PYTHON_VERSION-$PYPY3_VERSION-linux_x86_64-portable.tar.bz2 -C ~ && deactivate && ~/pypy$PYPY3_PYTHON_VERSION-$PYPY3_VERSION-linux_x86_64-portable/bin/virtualenv-pypy ~/pypy3-venv && . ~/pypy3-venv/bin/activate; fi"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "sudo apt-get -V install sox libsox-fmt-mp3"
script:
  - "coverage run --source=google_speech setup.py test"
after_success:
  - "coveralls"
deploy:
  provider: pypi
  user: desbma
  password:
    secure: "tjxJaCGWKWc6yPcQVsIpj+Z0wkVn5IQNIZWRkMSJ4AHSN5ZPMKzcAQtQgmRPK24h2Bi73lcCb/Ub4qDWnlHpkAubcmQciXpJWv2K1FWeD3X4TXOwWGQKBpWhK0UGwfTHhTrsv247qC3Y9m0F9qJFCIi58vWKI/XbLieBJuMYFOg="
  on:
    tags: true
    branch: master
    python: "3.6"
notifications:
  email:
    recipients:
      - secure: "Vzi/yzeFX5sQ1vAmEdLzKtKDXjYvfImtGdesr7XYGC5bKL1sTY8u8qgsf6kwXIztGn/TFgisKNkjfNVZL+GH+4+Edns4nY/ujLEV0pM7WfT0+DxFzuP4yNDSa6M1u2QjZsN30qHKkqmct8kxwnZexsDGQY5YSnIUZ7rVH92y/p0="
    on_success: always
    on_failure: always
