language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - "sudo apt-get -q update"
  - "pip install -U pip"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "sudo apt-get -yV install sox libsox-fmt-mp3"
script:
  - "export AUDIODEV=null"  # see https://github.com/travis-ci/travis-ci/issues/1754
  - "coverage run --source=google_speech setup.py test"
after_success:
  - "coveralls"
before_deploy:
  - "sudo add-apt-repository -y ppa:marutter/c2d4u"  # to get newer pandoc
  - "sudo apt-get -q update"
  - "sudo apt-get -yV install pandoc"
  - "pip install pypandoc"
deploy:
  provider: pypi
  user: desbma
  password:
    secure: "tjxJaCGWKWc6yPcQVsIpj+Z0wkVn5IQNIZWRkMSJ4AHSN5ZPMKzcAQtQgmRPK24h2Bi73lcCb/Ub4qDWnlHpkAubcmQciXpJWv2K1FWeD3X4TXOwWGQKBpWhK0UGwfTHhTrsv247qC3Y9m0F9qJFCIi58vWKI/XbLieBJuMYFOg="
  on:
    tags: true
notifications:
  email:
    recipients:
      - secure: "Vzi/yzeFX5sQ1vAmEdLzKtKDXjYvfImtGdesr7XYGC5bKL1sTY8u8qgsf6kwXIztGn/TFgisKNkjfNVZL+GH+4+Edns4nY/ujLEV0pM7WfT0+DxFzuP4yNDSa6M1u2QjZsN30qHKkqmct8kxwnZexsDGQY5YSnIUZ7rVH92y/p0="
    on_success: always
    on_failure: always
