language: python
python:
  - "3.3"
  - "3.4"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "sudo apt-get -yV install sox libsox-fmt-mp3"
script:
  - "export AUDIODEV=null"  # see https://github.com/travis-ci/travis-ci/issues/1754
  - "coverage run --source=google_speech setup.py test"
after_success:
  - "coveralls"
